#!/bin/bash
count=0
while IFS= read -r -d '' dir; do
    if [[ "$dir" != "." && "$dir" != ".." ]]; then
        ((count++))
    fi
done < <(find . -type d -print0)
echo "Number of directories and subdirectories: $count"
